Update README.md
valispace/ValispaceMatlabToolbox pull request #5
Opened 2024-04-29 14:04 UTC by antonio-soares-altium

Updated description of toolbox installation and management.

Deleted old Matlab App installation file and included new Toolbox installation file and updated Matlab Toolbox Project file.

2024-04-30 13:30 UTC, louise-lindblad-altium approved these changes, later dismissed
Looks good!

2024-10-03 10:53 UTC, caue-napier-altium approved these changes, later dismissed

2024-10-30 14:48 UTC, antonio-soares-altium reviewed
Basic commands tested and working

2024-10-31 10:35 UTC, antonio-perez-altium commented on src/ValispaceInit.m
>      end
@joao-goncalves-altium should we allow insecure connections to be established with our integrations??

2024-10-31 10:42 UTC, antonio-perez-altium approved these changes
As the majority of the dev team works now on Mac/Unix, I would suggest adding a warning on the README that this `.prj` file only supports Windows for development.

2024-10-31 10:42 UTC, antonio-perez-altium commented on ValispaceMatlabToolbox.prj
> +    <param.screenshot>C:\Users\anton.VALISPACE-SM-AS\OneDrive - Altium LLC\Pictures\Valispace\Valispace Logo.png</param.screenshot>
Exposing local path should not be done, please input reference in another way, either a relative file in the repo if possible or to a remote url

2024-10-31 10:43 UTC, antonio-perez-altium requested changes
Meant to request changes

2025-04-16 16:24 UTC, closed without merging